[features]
seeds = false
[programs.localnet]
basic1 = "3YF7DUAicx8VfhtAU9c3Tg9BW6dBYs1bfdKowRe5odvm"
[programs.devnet]
basic1 = "3YF7DUAicx8VfhtAU9c3Tg9BW6dBYs1bfdKowRe5odvm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/da/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
